version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: otp-ticket-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  partner-module:
    build:
      context: ./Partner
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - db

  ticket-service:
    build:
      context: ./TicketService
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/otp-ticket-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      API_BASE_URL: http://partner-module:8081/
    expose:
      - 8082
    ports:
      - "8082:8082"
    depends_on:
      - db
      - partner-module
