name: Ticket Service Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: otp-ticket-service
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Partner
      run: |
        cd Partner
        ./mvnw clean package

    - name: Test Partner
      run: |
        cd Partner
        ./mvnw test

    - name: Configure the application.properties file in Ticket Service
      run: |
          cd TicketService
          cat >./src/main/resources/application.properties <<EOF
          spring.datasource.url=jdbc:postgresql://localhost:5432/otp-ticket-service
          spring.datasource.username=postgres
          spring.datasource.password=admin
          spring.jpa.hibernate.ddl-auto=create
          spring.sql.init.mode=always
          spring.sql.init.schema-locations=classpath:init.sql
          spring.jpa.defer-datasource-initialization=true
          spring.jpa.hibernate.ddl-auto=create
          spring.datasource.driver-class-name=org.postgresql.Driver
          spring.config.import=optional:file:.env[.properties]
          server.port=8082
          EOF

    - name: Build TicketService
      run: |
        cd TicketService
        ./mvnw clean package -DskipTests=true

    - name: Test TicketService
      run: |
        cd TicketService
        ./mvnw test
