name: Ticket Service Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-partner:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Partner code
      uses: actions/checkout@v4
      with:
        path: Partner

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build and Test Partner
      run: ./Partner/mvnw clean package

  test-ticket-service:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout TicketService code
      uses: actions/checkout@v4
      with:
        path: TicketService

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build and Test TicketService
      run: ./TicketService/mvnw clean package
